### ISSUE TITLE
ummmmmmmmmmmmmmmmm

### ISSUE THREAD

**Issue by LayZNimrod** [imd1005-web-development-winter-2023/assignment-02-LayZNimrod#3]
The web page passes [W3C validation](https://validator.w3.org/#validate_by_uri)

I did not realize this was a requirement and I got errors for 21 things. Can I have a small bit of extra time to sort some issues out.

This is the link of what it says [link](https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-LayZNimrod%2F)

Idk if this link will work but I'm sending it anyway

**Comment by neilmispelaar** [comment]
Good catch @LayZNimrod !!!

Get some sleep. Tackle the validation errors in the next 48 hours without penalty. 

Good luck. Let me know if you need anything else. 

🛫

**Comment by LayZNimrod** [comment]
ok it should be all fixed now
